### PR TITLE
PLNSRVCE-1431: Fix the presence with enough concurrenct of negative values for 'pipelinerun_duration_between_taskruns_milliseconds_sum'

### PR DESCRIPTION
**Pull request by gabemontero**
initial testing in staging proved that with enough concurrency, the `Status.ChildReferences` array is minimally not sorted based on when the task runs were created, so we explicitly sort for that so we do not get negative values for the gap samples

for reference, the doc on specifying execution order:  https://tekton.dev/docs/pipelines/pipelines/#configuring-the-task-execution-order

This addresses parallel task runs at the start of a pipelinerun, different threads of taskrun dependency chains, and a final task run dependent on multiple threads/chains by

Also added 
- actual RHTAP staging runs which exhibited the negative number bug for validation
- unit tests for the controller runtime filters
- increased the validation of the actual metric data in the unit test to verify no negative numbers

### CODE REVIEW

**Review by ramessesii2 — COMMENTED** [review]
~~You missed to update the log message here - https://github.com/openshift-pipelines/pipeline-service-exporter/pull/34/files#diff-bacda4196256b80bde6a1f6a6cc19d08e3309a4418a179ac4a730135bf950825R224-R227.~~

#### Also I wanted to understand why dont we use the TaskRuns [DAG](https://tekton.dev/docs/pipelines/pipelines/#configuring-the-task-execution-order) structure itself?
```
        |            |
        v            v
     test-app    lint-repo
    /        \
   v          v
build-app  build-frontend
   \          /
    v        v
    deploy-all
```
 While sorting and then calculating gaps provides some insights into the timing between tasks, it doesn't fully capture the dependencies and execution flow within the pipeline.
The DAG approach would ensure that the gaps are calculated between TaskRuns that are meant to run sequentially, respecting the dependencies defined in the `runAfter` field. This avoids calculating gaps between tasks that could run in parallel, providing a more accurate representation of the timing between dependent tasks.

I might be wrong though if I'm missing the requirements for this metric. I'd happy to hear your thoughts. Thank you.

**Comment by gabemontero** [comment]
> You missed to update the log message here - https://github.com/openshift-pipelines/pipeline-service-exporter/pull/34/files#diff-bacda4196256b80bde6a1f6a6cc19d08e3309a4418a179ac4a730135bf950825R224-R227.

Sorry @ramessesii2, could you clarify what I missed updating exactly?  Or could you suggest what you thing the log message should be?  Thanks.

> #### Also I wanted to understand why dont we use the TaskRuns [DAG](https://tekton.dev/docs/pipelines/pipelines/#configuring-the-task-execution-order) structure itself?
> 
> ```
>         |            |
>         v            v
>      test-app    lint-repo
>     /        \
>    v          v
> build-app  build-frontend
>    \          /
>     v        v
>     deploy-all
> ```
> 
> While sorting and then calculating gaps provides some insights into the timing between tasks, it doesn't fully capture the dependencies and execution flow within the pipeline. The DAG approach would ensure that the gaps are calculated between TaskRuns that are meant to run sequentially, respecting the dependencies defined in the `runAfter` field. This avoids calculating gaps between tasks that could run in parallel, providing a more accurate representation of the timing between dependent tasks.
> 
> I might be wrong though if I'm missing the requirements for this metric. I'd happy to hear your thoughts. Thank you.

Very good question.  

Short answer: complexity vs. being "good enough" .... however, your question made me think about it enough that I realized a simpler (than redoing DAG logic which is not fully public in the tekton repo) but sufficient addition to this fix makes sense.

Longer answer:  `runAfter` processing would be a little more straight forward as its value is only the name of other tasks.  However, the `results` stuff is much more complicated, as you have to deal with the multitude of ways you reference results (params and when expressions) from prior tasks, as well as the variable substitution and parsing dot separated strings to infer the graph relationships.

And RHTAP uses both `runAfter` and `results`.

However, my realization after considering your question.  Our job is really simpler than tekton's.  We do not have to rebuild the DAG.  When considering a given TaskRun, if we simply consider the completion time of the TaskRun that was created before us, we should be able to use that to offset the additional time a TaskRun's creation had to wait while a prior TaskRun it depended on completed.

I'll make that change, and update this PR when it is ready.  Then, in the interim, please clarify what I needed to change in that log message, and we'll go from there.

Thanks.

**Comment by ramessesii2** [comment]
Hey Gabe, thanks for the reply. I've skimmed over your detailed explanation for now. 

> could you clarify what I missed updating exactly? 

I meant the [log message here](https://github.com/openshift-pipelines/pipeline-service-exporter/pull/34/files#diff-bacda4196256b80bde6a1f6a6cc19d08e3309a4418a179ac4a730135bf950825R225) is - `ctrl.Log.Info(fmt.Sprintf("could not calcuate gap for taskrun %s:%s: %s", pr.Namespace, kidRef.Name, err.Error()))`.
Ah! I see why it's good to go. Initially, I was thinking that those messages should appear later. But never mind and I'm  Sorry for the confusion.

And just found out a typo though `calcuate` -> `calculate` [here](https://github.com/openshift-pipelines/pipeline-service-exporter/pull/34/files#diff-bacda4196256b80bde6a1f6a6cc19d08e3309a4418a179ac4a730135bf950825R225)

**Comment by gabemontero** [comment]
> Hey Gabe, thanks for the reply. I've skimmed over your detailed explanation for now (since it's a bit late for me).
> 
> > could you clarify what I missed updating exactly?
> 
> I meant the [log message here](https://github.com/openshift-pipelines/pipeline-service-exporter/pull/34/files#diff-bacda4196256b80bde6a1f6a6cc19d08e3309a4418a179ac4a730135bf950825R225) is - `ctrl.Log.Info(fmt.Sprintf("could not calcuate gap for taskrun %s:%s: %s", pr.Namespace, kidRef.Name, err.Error()))`. Ah! I see why it's good to go. Initially, I was thinking that those messages should appear later. But never mind and I'm Sorry for the confusion.
> 
> And just found out a typo though `calcuate` -> `calculate` [here](https://github.com/openshift-pipelines/pipeline-service-exporter/pull/34/files#diff-bacda4196256b80bde6a1f6a6cc19d08e3309a4418a179ac4a730135bf950825R225)

ok I'll fix the typo, thanks @ramessesii2 

Also I just pushed the update for addressing parallel tasks, multiple chains of taskrun dependencies, etc. without building the entire tekton DAG library for building the execution graph.

**Comment by gabemontero** [comment]
FYI @ramessesii2 @enarha today I grabbed actual pipelinerun/taskrun yaml for one of the namespaces which was showing negative values for the stat, and am constructing a unit test that uses those, to better validate the fix.

I'll remove the do-not-merge / wip qualifiers on this PR's title once I've pushed the changes.

Thanks.

**Comment by gabemontero** [comment]
> FYI @ramessesii2 @enarha today I grabbed actual pipelinerun/taskrun yaml for one of the namespaces which was showing negative values for the stat, and am constructing a unit test that uses those, to better validate the fix.
> 
> I'll remove the do-not-merge / wip qualifiers on this PR's title once I've pushed the changes.
> 
> Thanks.

OK the unit test is up and working (it found some subtle issues with the prior form of the fix) @ramessesii2 @enarha 

I'll wait until Sunday/Monday for you all to get a chance to review before I merge.  Can't wait too much long after, given the performance wg desire for this metric.

**Review by ramessesii2 — DISMISSED** [review]
Thanks Gabe for addressing the review comments. 
To be honest, I found it a little complex to visualize the algorithm in action when it comes to large no. of parallel and dependent TaskRuns.  Though, the algorithm proposed is clear to me and the tests speak for its correctness. Also, picking up the PRs & TRs from staging for testing is a neat idea 😄 .

**Comment by gabemontero** [comment]
Per stand up today, I'm going to get this merged today, and any items @enarha finds after merge we'll do in a follow up PR.

Also, per stand up, I'm going to tweak the metric name, so as to not let the prior data influence future queries with a presumably functional metric, where we have to worry about updating any queries with offsets etc. to filter out the bad data.

Lastly, after standup, I just looked, and there was a restart of the exporter since I last looked end of last week.   We need to account for the taskrun completion timestamp to be nil.  Presumably this can occur on failed pipelineruns with multiple execution threads.

The stack trace was:
```
{"level":"info","ts":"2023-08-25T07:45:45Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"pipelinerun","controllerGroup":"tekton.dev","controllerKind":"PipelineRun","PipelineRun":{"name":"devfile-sample-drbn-pbzvt","namespace":"test-rhtap-71-tenant"},"namespace":"test-rhtap-71-tenant","name":"devfile-sample-drbn-pbzvt","reconcileID":"badec47e-12f6-41da-89bc-af9ea1e5a833"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1660a11]
goroutine 829 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:119 +0x1fa
panic({0x17e6260, 0x292e420})
/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/openshift-pipelines/pipeline-service-exporter/collector.(*PipelineRunTaskRunGapCollector).bumpGapDuration(0xc0009b1ec0, 0xc009465680, {0x1cb0c48, 0xc000e5ede0}, {0x1ca9290, 0xc006e44540})
/workspace/collector/collector.go:252 +0x651
github.com/openshift-pipelines/pipeline-service-exporter/collector.(*ReconcilePipelineRunTaskRunGap).Reconcile(0xc000e67a40, {0x1ca9338?, 0xc005df7e90?}, {{{0xc0090bca68, 0x14}, {0xc0088a4080, 0x19}}})
/workspace/collector/pipelinerun.go:171 +0x338
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1ca9338?, {0x1ca9338?, 0xc005df7e90?}, {{{0xc0090bca68?, 0x175e800?}, {0xc0088a4080?, 0x0?}}})
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001c3d60, {0x1ca9290, 0xc000e59400}, {0x1849aa0?, 0xc00544fc00?})
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323 +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001c3d60, {0x1ca9290, 0xc000e59400})
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
/root/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:231 +0x33
```

Based on the current commit level, the key line number and which line of code it corresponds to:
```
https://github.com/openshift-pipelines/pipeline-service-exporter/blob/46a602d3cf1d7054f391e3b41042d6e9787272e9/collector/collector.go#L252
gap := kid.CreationTimestamp.Time.Sub(prevKid.Status.CompletionTime.Time).Milliseconds()
```

**Review by enarha — APPROVED** [review]

**Pull request merged**
